name: vetwork_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 2.0.4+54

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  #device_id: ^0.2.0
  device_info: ^0.4.0+1
  http: ^0.12.0+1
  shared_preferences: ^0.5.1+2
  google_maps_flutter: ^0.0.3
  flutter_google_places: ^0.1.4
  location: ^1.4.1
  geocoder: ^0.2.1
  image_picker: 0.4.12+1
  scoped_model: ^1.0.1
  intl: ^0.15.8
  firebase_messaging: ^4.0.0+4
  flutter_launcher_icons: ^0.7.0
  flutter_verification_code_input:
    git:
      url: git://github.com/tinylife-io/flutter_verification_code_input.git




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
    ios: true
    android: true
    image_path_ios: "assets/pics/applogoiosstore.png"
    image_path_android: "assets/pics/applogo.png"
    adaptive_icon_background: "assets/pics/applogo.png"
    adaptive_icon_foreground: "assets/pics/applogo.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
   - assets/pics/credit_card.png
   - assets/pics/visa.png
   - assets/pics/track.jpg
   - assets/pets/applogo.png
   - assets/pets/cat.png
   - assets/pets/dog.png
   - assets/pets/other.png
   - assets/pets/health.png
   - assets/pets/grooming.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
